name: main
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR coveralls comments
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# no need to bother caching bun deps
# https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221
jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_ts_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: |
            {src,test}/**/*.ts
            package.json
            tsconfig.json

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            "check:format" = { run = "dprint check --excludes mise.toml" }
            "check:lint" = { run = "biome check" }
            "check:types" = { run = "tsc" }
            "check" = { depends = "check:*" }
            [tools]
            bun = "latest"
            dprint = "latest"
            "npm:@biomejs/biome" = "latest"
            "npm:typescript" = "latest"
      - run: bun i
      - run: mise r check
